### ISSUE TITLE
Sonoma installer doesn't launch

### ISSUE THREAD

**Issue by RikuKunMS2** [rowell1/GPD-WIN-Max-2020-Hackintosh#1]
I think there are some issues with the EFI set, the one from http://b00tb00k.blogspot.com/2021/02/gpd-win-maxhackintosh_11.html Works for ventura, but not Sonoma

Maybe there are some variations between units but I think we need to update the the USB Hub ssdt 

also the above link contains the bios link patch and a slightly more in depth install guide on how to get it set up from scratch.

**Comment by RikuKunMS2** [comment]
I got it working, apparently there are a bunch of config plist things to set before going into the installer

You need to add a kext, set your boot arg to and then ALSO disable secure boot then the installer will launch.

During the update / install process. disable the AirportItlwm kext that you have, and plan to update to the latest MacOS 14.4 compatible AirportItlwm later, once you are running 14.4. This fixes reboot/crash issues because MacOS 14.4 can't boot up with the older versions of airportitlwm. To add more clarity:

Change (in config.plist of your boot EFI) Misc->Security->SecureBootModel to DISABLED. This fixes an issue where MacOS 14.4 upgrade (or new install) will start to install but will constantly reboot after the first (install-driven) reboot.

If you aren't offered MacOS updates via SystemSettings/General/SoftwareUpdate, download and install RestrictEvents.kext and then add "revpatch=sbvmm" to your boot args in NVRAM section of config.plist.

**Comment by RikuKunMS2** [comment]
I got it working, apparently there are a bunch of config plist things to set before going into the installer

You need to add a kext, set your boot arg to and then ALSO disable secure boot then the installer will launch.

During the update / install process. disable the AirportItlwm kext that you have, and plan to update to the latest MacOS 14.4 compatible AirportItlwm later, once you are running 14.4. This fixes reboot/crash issues because MacOS 14.4 can't boot up with the older versions of airportitlwm. To add more clarity:

Change (in config.plist of your boot EFI) Misc->Security->SecureBootModel to DISABLED. This fixes an issue where MacOS 14.4 upgrade (or new install) will start to install but will constantly reboot after the first (install-driven) reboot.

If you aren't offered MacOS updates via SystemSettings/General/SoftwareUpdate, download and install RestrictEvents.kext and then add "revpatch=sbvmm" to your boot args in NVRAM section of config.plist.

**Comment by rowell1** [comment]
Thx @RikuKunMS2, your input on this project is greatly appreciated.

P2 Max 2019 and WIN Max 2020 have similar hardware, so my first attempt with an updated @b00t0x's EFI folder is already promising:  OpenCore (TXT and) GUI boot menu (from top to bottom) is rotated ~~90 (CW)~~ 270 degrees (CCW) and when Sonoma 14.5 Recovery starts, it falls back to normal 0 degrees , but the keyboard of my P2Max 2019 is not recognized...

(Note: I am testing the WIN Max 2020 EFI folder on my P2 Max 2019)

**Comment by RikuKunMS2** [comment]
The proper rotation is 270 degrees, I’m not sure how he fixed it in the boot menus but my 2020 ice lake win max isn’t rotated in canopy or non canopy open core the installer and os will show up 90 degrees though at the end he has an app that can help fix the rotation to 270 once you’re logged into the os

**Comment by rowell1** [comment]
Found  _NVRAM > Add > 7C436110-AB2A-4BBB-A880-FE41995C9F82 > ForceDisplayRotationInEFI=**90**_ in config.plist:  
• WIN Max 2020 uses a 8”  1280x800 portrait screen		—>	display shows no rotation  
• P2 Max 2019 uses a 10.1” 2560x1600 landscape screen	—>	display shows -90 degrees (CW) rotation  
_source: https://wiki.archlinux.org/title/GPD_Win_Max#Screen_rotation_

**Comment by RikuKunMS2** [comment]
Wanted to let you know I got Sonoma fully installed and everything working (except hdmi and digital audio via DisplayPort or hdmi but that's an ice lake limitiation)

You'll need to make sure you have the debug version of open core to use the Sonoma 2.3 WiFi kext

Make sure to clear you nvram too after you're done installing 

You'll need two efi configs one for the install and another for normal runs without the restrict events and secure boot settings we used for the installer above

One last note is to make sure your smbios is set correct as in Sonoma only supports the MacBook Air 2018 and up (which most guides use an older model) so you'll have to make sure that's updated as well

**Comment by RikuKunMS2** [comment]
More info:

For iservices to work, make sure you enable on Ventura then upgrade to Sonoma. Then use a null ethernet kext and then on login toggle on and toggle off Ethernet (make sure ethernet is set to 1st position in system settings) 
you can do this with automator:
pause 10 seconds
run shell
networksetup -setnetworkserviceenabled "Ethernet" on
pause 2 seconds
run shell
networksetup -setnetworkserviceenabled "Ethernet" off

make an app then add it as a login item;

Also i had some audio issues, so I set the alcid to 100 in the boot args as that's the same as the p2 max
